/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import javax.swing.JOptionPane;

/**
 *
 * @author chandrabahadurkc
 */
public class CheckEmail extends javax.swing.JFrame {

    /**
     * Creates new form CheckEmail
     */
    public CheckEmail() {
        initComponents();
        
        setupOTPField(txtOne, txtTwo, null);
    setupOTPField(txtTwo, txtThree, txtOne);
    setupOTPField(txtThree, txtFour, txtTwo);
    setupOTPField(txtFour, txtFive, txtThree);
    setupOTPField(txtFive, txtSix, txtFour);
    setupOTPField(txtSix, null, txtFive);

    verify.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            String code = getOTPCode();
            if (code.length() < 6) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter all 6 digits.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Entered OTP: " + code);
                // TODO: Add OTP validation logic here
            }
        }
    });
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkemail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        verify = new javax.swing.JButton();
        txtOne = new javax.swing.JTextField();
        txtTwo = new javax.swing.JTextField();
        txtThree = new javax.swing.JTextField();
        txtFour = new javax.swing.JTextField();
        txtFive = new javax.swing.JTextField();
        txtSix = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        checkemail.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        checkemail.setText(" Check Your Email");

        jLabel1.setText("Enter the confirmation code we sent to your email an*****@gmail.com");

        verify.setBackground(new java.awt.Color(153, 0, 0));
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setText("Next");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        txtOne.setText("0");
        txtOne.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOneFocusLost(evt);
            }
        });
        txtOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOneActionPerformed(evt);
            }
        });

        txtTwo.setText("0");
        txtTwo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTwoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTwoFocusLost(evt);
            }
        });

        txtThree.setText("0");
        txtThree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtThreeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtThreeFocusLost(evt);
            }
        });
        txtThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThreeActionPerformed(evt);
            }
        });

        txtFour.setText("0");
        txtFour.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFourFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFourFocusLost(evt);
            }
        });
        txtFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFourActionPerformed(evt);
            }
        });

        txtFive.setText("0");
        txtFive.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFiveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFiveFocusLost(evt);
            }
        });
        txtFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiveActionPerformed(evt);
            }
        });

        txtSix.setText("0");
        txtSix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSixFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSixFocusLost(evt);
            }
        });
        txtSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSixActionPerformed(evt);
            }
        });

        jButton2.setText(" Send code again");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText(" Didn't recive the code.");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forgetpassword/Screenshot 2025-05-23 at 11.41.41.png"))); // NOI18N
        jLabel3.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtOne, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtThree, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtFour, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFive, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSix, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(checkemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOne, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtTwo)
                    .addComponent(txtFour)
                    .addComponent(txtThree)
                    .addComponent(txtFive)
                    .addComponent(txtSix))
                .addGap(36, 36, 36)
                .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOneActionPerformed

    private void txtThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThreeActionPerformed

    private void txtFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFourActionPerformed

    private void txtFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiveActionPerformed

    private void txtSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSixActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtOneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOneFocusGained
        // TODO add your handling code here:
        if (txtOne.getText().equals("0")){
            txtOne.setText("");
        }
    }//GEN-LAST:event_txtOneFocusGained

    private void txtTwoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTwoFocusGained
        // TODO add your handling code here:
        if (txtTwo.getText().equals("0")){
            txtTwo.setText("");
        }
    }//GEN-LAST:event_txtTwoFocusGained

    private void txtThreeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThreeFocusGained
        // TODO add your handling code here:
        if (txtThree.getText().equals("0")){
            txtThree.setText("");
        }
    }//GEN-LAST:event_txtThreeFocusGained

    private void txtFourFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFourFocusGained
        // TODO add your handling code here:
        if (txtFour.getText().equals("0")){
            txtFour.setText("");
        }
    }//GEN-LAST:event_txtFourFocusGained

    private void txtFiveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiveFocusGained
        // TODO add your handling code here:
        if (txtFive.getText().equals("0")){
            txtFive.setText("");
        }
    }//GEN-LAST:event_txtFiveFocusGained

    private void txtSixFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSixFocusGained
        // TODO add your handling code here:
        if (txtSix.getText().equals("0")){
            txtSix.setText("");
        }
    }//GEN-LAST:event_txtSixFocusGained

    private void txtSixFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSixFocusLost
        // TODO add your handling code here:
        if (txtSix.getText().isEmpty()){
            txtSix.setText("0");
        }
    }//GEN-LAST:event_txtSixFocusLost

    private void txtFiveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiveFocusLost
        // TODO add your handling code here:
        if (txtFive.getText().isEmpty()){
            txtFive.setText("0");
        }
    }//GEN-LAST:event_txtFiveFocusLost

    private void txtFourFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFourFocusLost
        // TODO add your handling code here:
        if (txtFour.getText().isEmpty()){
            txtFour.setText("0");
        }
    }//GEN-LAST:event_txtFourFocusLost

    private void txtThreeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThreeFocusLost
        // TODO add your handling code here:
        if (txtThree.getText().isEmpty()){
            txtThree.setText("0");
        }
    }//GEN-LAST:event_txtThreeFocusLost

    private void txtTwoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTwoFocusLost
        // TODO add your handling code here:
        if (txtTwo.getText().isEmpty()){
            txtTwo.setText("0");
        }
    }//GEN-LAST:event_txtTwoFocusLost

    private void txtOneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOneFocusLost
        // TODO add your handling code here:
        if (txtOne.getText().isEmpty()){
            txtOne.setText("0");
        }
    }//GEN-LAST:event_txtOneFocusLost

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(CheckEmail.this,"OTP Verified.");
        new NewPassword().setVisible(true);
    }//GEN-LAST:event_verifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkemail;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFive;
    private javax.swing.JTextField txtFour;
    private javax.swing.JTextField txtOne;
    private javax.swing.JTextField txtSix;
    private javax.swing.JTextField txtThree;
    private javax.swing.JTextField txtTwo;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
    
    private void setupOTPField(javax.swing.JTextField current, javax.swing.JTextField next, javax.swing.JTextField prev) {
        current.setDocument(new JTextFieldLimit(1));
        current.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        current.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));

        current.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar()) || current.getText().length() == 1) {
                    e.consume();
                }
            }

            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                if (e.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    if (current.getText().isEmpty() && prev != null) {
                        prev.requestFocus();
                    }
                } else if (current.getText().length() == 1) {
                    if (next != null) {
                        next.requestFocus();
                    } else {
                        verify.doClick(); // auto-submit
                    }
                }
            }
        });
    }

    // Combine 6 digits into one string
    private String getOTPCode() {
        return txtOne.getText() + txtTwo.getText() + txtThree.getText()
             + txtFour.getText() + txtFive.getText() + txtSix.getText();
    }

    // Custom Document to restrict field to one character
    class JTextFieldLimit extends javax.swing.text.PlainDocument {
    private final int limit;

    public JTextFieldLimit(int limit) {
        this.limit = limit;
    }

    @Override
    public void insertString(int offset, String str, javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
        if (str == null) return;

        // Only allow one character total in the field
        if (getLength() + str.length() <= limit) {
            super.insertString(offset, str, attr);
        }
    }
}



}
