/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.LoggedInUser;
import Model.Notes;
import controller.LoginController;
import controller.NoteController;
import cookbook.Dashboard;
import static cookbook.Dashboard.Main_panel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author LEGION
 */
public class SelfNote extends javax.swing.JFrame {
 private NoteController noteController;
 
    /**
     * Creates new form SelfNote
     */
    public SelfNote() { 
        initComponents();
        setupAddNoteButton();
        setLocationRelativeTo(null);
//        setSize(920, 707);
        
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        
        noteContainer.setLayout(new BoxLayout(noteContainer, BoxLayout.Y_AXIS));
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
//        new NoteController(this).loadNotes();
        this.noteController = new NoteController(this);
        noteController.loadNotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_panel = new javax.swing.JPanel();
        Category_panel = new javax.swing.JPanel();
        Category = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Selfnote_panel = new javax.swing.JPanel();
        selfNote = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Logo_label = new javax.swing.JLabel();
        Settings_panel = new javax.swing.JPanel();
        Settings = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Myprofile_panel = new javax.swing.JPanel();
        myProfile = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Logout_panel = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        Bookmark_panel = new javax.swing.JPanel();
        Bookmarkbutton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        Challenges_panel = new javax.swing.JPanel();
        Challenges = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        Home_panel = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Search_panel = new javax.swing.JPanel();
        Search_border = new javax.swing.JPanel();
        Searchicon_label = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        Filtericon_label = new javax.swing.JLabel();
        Filters = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        emptyMessageLabel = new javax.swing.JLabel();
        addNoteButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        noteContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu_panel.setBackground(new java.awt.Color(255, 255, 255));
        Menu_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Menu_panel.setMaximumSize(new java.awt.Dimension(241, 982));
        Menu_panel.setMinimumSize(new java.awt.Dimension(241, 982));

        Category_panel.setBackground(new java.awt.Color(255, 255, 255));

        Category.setText("Category");
        Category.setBorder(null);
        Category.setBorderPainted(false);
        Category.setContentAreaFilled(false);
        Category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Category_panelLayout = new javax.swing.GroupLayout(Category_panel);
        Category_panel.setLayout(Category_panelLayout);
        Category_panelLayout.setHorizontalGroup(
            Category_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Category_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Category)
                .addContainerGap())
        );
        Category_panelLayout.setVerticalGroup(
            Category_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Category_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Category_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        Selfnote_panel.setBackground(new java.awt.Color(255, 255, 255));

        selfNote.setText("Self Note");
        selfNote.setBorder(null);
        selfNote.setBorderPainted(false);
        selfNote.setContentAreaFilled(false);
        selfNote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selfNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selfNoteMouseClicked(evt);
            }
        });
        selfNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selfNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Selfnote_panelLayout = new javax.swing.GroupLayout(Selfnote_panel);
        Selfnote_panel.setLayout(Selfnote_panelLayout);
        Selfnote_panelLayout.setHorizontalGroup(
            Selfnote_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Selfnote_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selfNote)
                .addContainerGap())
        );
        Selfnote_panelLayout.setVerticalGroup(
            Selfnote_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Selfnote_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selfNote, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Settings_panel.setBackground(new java.awt.Color(255, 255, 255));

        Settings.setText("Settings");
        Settings.setBorder(null);
        Settings.setBorderPainted(false);
        Settings.setContentAreaFilled(false);
        Settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Settings_panelLayout = new javax.swing.GroupLayout(Settings_panel);
        Settings_panel.setLayout(Settings_panelLayout);
        Settings_panelLayout.setHorizontalGroup(
            Settings_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Settings)
                .addContainerGap())
        );
        Settings_panelLayout.setVerticalGroup(
            Settings_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Settings, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Myprofile_panel.setBackground(new java.awt.Color(255, 255, 255));

        myProfile.setText("My Profile");
        myProfile.setBorder(null);
        myProfile.setBorderPainted(false);
        myProfile.setContentAreaFilled(false);
        myProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Myprofile_panelLayout = new javax.swing.GroupLayout(Myprofile_panel);
        Myprofile_panel.setLayout(Myprofile_panelLayout);
        Myprofile_panelLayout.setHorizontalGroup(
            Myprofile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Myprofile_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myProfile)
                .addContainerGap())
        );
        Myprofile_panelLayout.setVerticalGroup(
            Myprofile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Myprofile_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Logout_panel.setBackground(new java.awt.Color(255, 255, 255));

        logOut.setText("Log Out");
        logOut.setBorder(null);
        logOut.setBorderPainted(false);
        logOut.setContentAreaFilled(false);
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Logout_panelLayout = new javax.swing.GroupLayout(Logout_panel);
        Logout_panel.setLayout(Logout_panelLayout);
        Logout_panelLayout.setHorizontalGroup(
            Logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Logout_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOut)
                .addGap(124, 124, 124))
        );
        Logout_panelLayout.setVerticalGroup(
            Logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        Bookmark_panel.setBackground(new java.awt.Color(255, 255, 255));

        Bookmarkbutton.setText("Bookmark");
        Bookmarkbutton.setBorder(null);
        Bookmarkbutton.setBorderPainted(false);
        Bookmarkbutton.setContentAreaFilled(false);
        Bookmarkbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bookmarkbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookmarkbuttonMouseClicked(evt);
            }
        });
        Bookmarkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookmarkbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Bookmark_panelLayout = new javax.swing.GroupLayout(Bookmark_panel);
        Bookmark_panel.setLayout(Bookmark_panelLayout);
        Bookmark_panelLayout.setHorizontalGroup(
            Bookmark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Bookmark_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bookmarkbutton)
                .addContainerGap())
        );
        Bookmark_panelLayout.setVerticalGroup(
            Bookmark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Bookmark_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Bookmark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bookmarkbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        Challenges_panel.setBackground(new java.awt.Color(255, 255, 255));

        Challenges.setText("Challenges");
        Challenges.setBorder(null);
        Challenges.setBorderPainted(false);
        Challenges.setContentAreaFilled(false);
        Challenges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Challenges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChallengesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Challenges_panelLayout = new javax.swing.GroupLayout(Challenges_panel);
        Challenges_panel.setLayout(Challenges_panelLayout);
        Challenges_panelLayout.setHorizontalGroup(
            Challenges_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Challenges_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Challenges)
                .addContainerGap())
        );
        Challenges_panelLayout.setVerticalGroup(
            Challenges_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Challenges_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Challenges_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Challenges, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        Home_panel.setBackground(new java.awt.Color(127, 1, 31));

        Home.setBackground(new java.awt.Color(127, 1, 31));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("Home");
        Home.setBorder(null);
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Home_panelLayout = new javax.swing.GroupLayout(Home_panel);
        Home_panel.setLayout(Home_panelLayout);
        Home_panelLayout.setHorizontalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Home)
                .addContainerGap())
        );
        Home_panelLayout.setVerticalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Screenshot 2025-06-22 192617.png"))); // NOI18N

        javax.swing.GroupLayout Menu_panelLayout = new javax.swing.GroupLayout(Menu_panel);
        Menu_panel.setLayout(Menu_panelLayout);
        Menu_panelLayout.setHorizontalGroup(
            Menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Menu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logo_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Menu_panelLayout.createSequentialGroup()
                .addGroup(Menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Category_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Challenges_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Selfnote_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bookmark_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Menu_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Settings_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Myprofile_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Logout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Menu_panelLayout.setVerticalGroup(
            Menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(32, 32, 32)
                .addComponent(Home_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Category_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Challenges_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bookmark_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selfnote_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Settings_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Myprofile_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Search_panel.setBackground(new java.awt.Color(255, 255, 255));
        Search_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Search_panel.setMaximumSize(new java.awt.Dimension(1512, 108));
        Search_panel.setMinimumSize(new java.awt.Dimension(1512, 108));

        Search_border.setMaximumSize(new java.awt.Dimension(526, 48));
        Search_border.setMinimumSize(new java.awt.Dimension(526, 48));

        Search.setText("Search");
        Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFocusLost(evt);
            }
        });

        Filters.setBackground(new java.awt.Color(242, 242, 242));
        Filters.setText("Filters");
        Filters.setBorder(null);
        Filters.setBorderPainted(false);
        Filters.setContentAreaFilled(false);
        Filters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Search_borderLayout = new javax.swing.GroupLayout(Search_border);
        Search_border.setLayout(Search_borderLayout);
        Search_borderLayout.setHorizontalGroup(
            Search_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_borderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Searchicon_label)
                .addGroup(Search_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Search_borderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Filtericon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(Search_borderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Filters)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Search_borderLayout.setVerticalGroup(
            Search_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_borderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Search_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Search_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Filtericon_label)
                        .addComponent(Filters))
                    .addComponent(Searchicon_label))
                .addContainerGap())
        );

        javax.swing.GroupLayout Search_panelLayout = new javax.swing.GroupLayout(Search_panel);
        Search_panel.setLayout(Search_panelLayout);
        Search_panelLayout.setHorizontalGroup(
            Search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Search_border, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Search_panelLayout.setVerticalGroup(
            Search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Search_border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        emptyMessageLabel.setText("Click + to create your first note");

        addNoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Screenshot 2025-06-15 193410.png"))); // NOI18N
        addNoteButton.setToolTipText("Create New Note");
        addNoteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        noteContainer.setLayout(new javax.swing.BoxLayout(noteContainer, javax.swing.BoxLayout.LINE_AXIS));
        scrollPane.setViewportView(noteContainer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emptyMessageLabel)
                            .addComponent(scrollPane)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNoteButton)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNoteButton)
                .addGap(3, 3, 3)
                .addComponent(emptyMessageLabel)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 717, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryActionPerformed

    private void selfNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selfNoteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selfNoteMouseClicked

    private void selfNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selfNoteActionPerformed
        // TODO add your handling code here:
//        CardLayout cl = (CardLayout)(Main_panel.getLayout());
//        cl.show(Main_panel, "selfnote");  // Show your custom panel
    }//GEN-LAST:event_selfNoteActionPerformed

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsActionPerformed

    private void myProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myProfileActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        //        Sigininframe sigin = new Sigininframe();
        //        LoginController controller = new LoginController(sigin);
        //
        //        controller.open();
        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
            null,
            "Do you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Proceed with logout
            Sigininframe sigin = new Sigininframe();
            LoginController controller = new LoginController(sigin);
            controller.open();

            // Close current window (if this is a JFrame)
            this.dispose(); // optional: closes the current window
        } else {
            // Logout cancelled
            System.out.println("Logout cancelled by user.");
        }
    }//GEN-LAST:event_logOutActionPerformed

    private void BookmarkbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookmarkbuttonMouseClicked
        // TODO add your handling code here:
//        java.awt.CardLayout cl = (java.awt.CardLayout)(Main_panel.getLayout());
//        cl.show(Main_panel, "bookmark");
    }//GEN-LAST:event_BookmarkbuttonMouseClicked

    private void BookmarkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookmarkbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookmarkbuttonActionPerformed

    private void ChallengesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChallengesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChallengesActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout)(Main_panel.getLayout());
        cl.show(Main_panel, "home");
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusGained
        // TODO add your handling code here:
        if(Search.getText().equals("Search")){
            Search.setText("");
        }
    }//GEN-LAST:event_SearchFocusGained

    private void SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusLost
        // TODO add your handling code here:
        if (Search.getText().isEmpty()) {
            Search.setText("Search");
        }
    }//GEN-LAST:event_SearchFocusLost

    private void FiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelfNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelfNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelfNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelfNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelfNote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bookmark_panel;
    private javax.swing.JButton Bookmarkbutton;
    private javax.swing.JButton Category;
    private javax.swing.JPanel Category_panel;
    private javax.swing.JButton Challenges;
    private javax.swing.JPanel Challenges_panel;
    private javax.swing.JLabel Filtericon_label;
    private javax.swing.JButton Filters;
    private javax.swing.JButton Home;
    private javax.swing.JPanel Home_panel;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JPanel Logout_panel;
    private javax.swing.JPanel Menu_panel;
    private javax.swing.JPanel Myprofile_panel;
    private javax.swing.JTextField Search;
    private javax.swing.JPanel Search_border;
    private javax.swing.JPanel Search_panel;
    private javax.swing.JLabel Searchicon_label;
    private javax.swing.JPanel Selfnote_panel;
    private javax.swing.JButton Settings;
    private javax.swing.JPanel Settings_panel;
    private javax.swing.JButton addNoteButton;
    private javax.swing.JLabel emptyMessageLabel;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton myProfile;
    private javax.swing.JPanel noteContainer;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton selfNote;
    // End of variables declaration//GEN-END:variables

public void showEmptyMessage() {
    emptyMessageLabel.setVisible(true);
    noteContainer.removeAll();
    noteContainer.revalidate();
    noteContainer.repaint();
}

public void clearNotePanel() {
    emptyMessageLabel.setVisible(false);
    noteContainer.removeAll();
    noteContainer.revalidate();
    noteContainer.repaint();
}
//public void addBookmarkListener(ActionListener listener) {
//    BookmarkButton.addActionListener(listener);
//}

// public void refreshNotes() {
//     jPanel1.removeAll(); // Clear old notes

//     NoteController controller = new NoteController(this);
//     java.util.List<Notes> notes = controller.getNotesByUserId(LoggedInUser.getId());

//     for (Notes note : notes) {
//         JPanel notePanel = new JPanel(new BorderLayout());
//         notePanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//         notePanel.setBackground(Color.WHITE);

//         JLabel titleLabel = new JLabel("Title: " + note.getTitle());
//         JTextArea contentArea = new JTextArea(note.getContent());
//         contentArea.setLineWrap(true);
//         contentArea.setWrapStyleWord(true);
//         contentArea.setEditable(false);

//         JButton editBtn = new JButton("Edit");
//         JButton deleteBtn = new JButton("Delete");

//         editBtn.addActionListener(e -> {
//             String newTitle = JOptionPane.showInputDialog(this, "Edit Title", note.getTitle());
//             String newContent = JOptionPane.showInputDialog(this, "Edit Content", note.getContent());
//             if (newTitle != null && newContent != null) {
//                 note.setTitle(newTitle);
//                 note.setContent(newContent);
//                 new NoteController(this).updateNote(note);
//             }
//         });

//         deleteBtn.addActionListener(e -> {
//             int confirm = JOptionPane.showConfirmDialog(this, "Delete this note?");
//             if (confirm == JOptionPane.YES_OPTION) {
//                 new NoteController(this).deleteNote(note.getId());
//             }
//         });

//         JPanel buttonPanel = new JPanel();
//         buttonPanel.add(editBtn);
//         buttonPanel.add(deleteBtn);

//         notePanel.add(titleLabel, BorderLayout.NORTH);
//         notePanel.add(new JScrollPane(contentArea), BorderLayout.CENTER);
//         notePanel.add(buttonPanel, BorderLayout.SOUTH);

//         jPanel1.add(notePanel);
//     }

//     jPanel1.revalidate();
//     jPanel1.repaint();
// }

// 

public void refreshNotes() {
    noteContainer.removeAll(); // Clear previous notes

    List<Notes> notes = noteController.getNotesByUserId(LoggedInUser.getId());

    if (notes == null || notes.isEmpty()) {
        JLabel emptyLabel = new JLabel("No notes found. Click + to add a new note.");
        emptyLabel.setFont(new Font("Arial", Font.ITALIC, 14));
        emptyLabel.setHorizontalAlignment(SwingConstants.CENTER);
        noteContainer.add(emptyLabel);
    } else {
        for (Notes note : notes) {
            JPanel notePanel = new JPanel(new BorderLayout());
            notePanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            notePanel.setBackground(Color.WHITE);
            notePanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 150));

            JLabel titleLabel = new JLabel("Title: " + note.getTitle());
            JTextArea contentArea = new JTextArea(note.getContent());
            contentArea.setLineWrap(true);
            contentArea.setWrapStyleWord(true);
            contentArea.setEditable(false);

            JButton editBtn = new JButton("Edit");
            JButton deleteBtn = new JButton("Delete");

            editBtn.addActionListener(e -> {
                String newTitle = JOptionPane.showInputDialog(this, "Edit Title", note.getTitle());
                String newContent = JOptionPane.showInputDialog(this, "Edit Content", note.getContent());
                if (newTitle != null && newContent != null) {
                    note.setTitle(newTitle);
                    note.setContent(newContent);
                    noteController.updateNote(note);
                }
            });

            deleteBtn.addActionListener(e -> {
                int confirm = JOptionPane.showConfirmDialog(this, "Delete this note?");
                if (confirm == JOptionPane.YES_OPTION) {
                    noteController.deleteNote(note.getId());
                }
            });

            JPanel buttonPanel = new JPanel();
            buttonPanel.add(editBtn);
            buttonPanel.add(deleteBtn);

            notePanel.add(titleLabel, BorderLayout.NORTH);
            notePanel.add(new JScrollPane(contentArea), BorderLayout.CENTER);
            notePanel.add(buttonPanel, BorderLayout.SOUTH);

            noteContainer.add(notePanel);
        }
    }

    noteContainer.revalidate();
    noteContainer.repaint();
}



public void addNoteToPanel(Notes note, NoteController controller) {
    JPanel notePanel = new JPanel();
    notePanel.setLayout(new BorderLayout());
    notePanel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    notePanel.setBackground(Color.WHITE);

    JLabel titleLabel = new JLabel(note.getTitle());
    JTextArea contentArea = new JTextArea(note.getContent());
    contentArea.setEditable(false);
    contentArea.setLineWrap(true);
    contentArea.setWrapStyleWord(true);

    JButton editBtn = new JButton("Edit");
    JButton deleteBtn = new JButton("Delete");

    JPanel btnPanel = new JPanel();
    btnPanel.add(editBtn);
    btnPanel.add(deleteBtn);

    notePanel.add(titleLabel, BorderLayout.NORTH);
    notePanel.add(new JScrollPane(contentArea), BorderLayout.CENTER);
    notePanel.add(btnPanel, BorderLayout.SOUTH);

    noteContainer.add(notePanel);
    noteContainer.revalidate();
    noteContainer.repaint();

    // Event handlers
    editBtn.addActionListener(e -> {
        String newTitle = JOptionPane.showInputDialog(this, "Edit Title", note.getTitle());
        String newContent = JOptionPane.showInputDialog(this, "Edit Content", note.getContent());
        if (newTitle != null && newContent != null) {
            note.setTitle(newTitle);
            note.setContent(newContent);
            controller.updateNote(note);
        }
    });

    deleteBtn.addActionListener(e -> {
        int confirm = JOptionPane.showConfirmDialog(this, "Delete this note?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            controller.deleteNote(note.getId());
        }
    });
}

private void setupAddNoteButton(){
    addNoteButton.addActionListener( e-> {
        String title = JOptionPane.showInputDialog(this, "Enter Note Title");
        String content = JOptionPane.showInputDialog(this, "Enter Note Content");
        
        if(title != null && content != null && !title.trim().isEmpty()){
            Notes note = new Notes(LoggedInUser.getId(), title , content);
            new NoteController(this).saveNote(note);
        }
        
    });
}

public void addSettingsListener(ActionListener listener){
    Settings.addActionListener(listener);
}

public void addUserMyProfileListener(ActionListener listener){
    myProfile.addActionListener(listener);
}

}