/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cookbook;

import DAO.RecipeDAO;
import Model.Recipe;
import controller.AdminDashboardController;
import javax.swing.JPanel;

/**
 *
 * @author Jay pradhan
 */
public class edit extends javax.swing.JPanel {

    /**
     * Creates new form edit
     */
    private final RecipeDAO recipeDAO;
private final AdminDashboardController controller;
private final update updatePanel; 
private final javax.swing.JPanel mainPanel; 
public edit(RecipeDAO recipeDAO, AdminDashboardController controller, JPanel mainPanel, update updatePanel) {
    initComponents();
    this.recipeDAO = recipeDAO;
    this.controller = controller;
    this.mainPanel = mainPanel;
    this.updatePanel = updatePanel;
}

     private int currentRecipeId;
     

    public void setRecipeId(int recipeId) {
        this.currentRecipeId = recipeId;
    }

    public int getRecipeId() {
        return currentRecipeId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose what you want to do?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(deleteButton)
                        .addGap(89, 89, 89)
                        .addComponent(updateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this recipe?",
        "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        boolean deleted = recipeDAO.deleteRecipe(currentRecipeId);

        if (deleted) {
            javax.swing.JOptionPane.showMessageDialog(this, "Recipe deleted successfully.");
            controller.loadRecipesToHome(); // Refresh home
            controller.loadBookmarkedRecipes(); // Refresh bookmarks
             // Reload homepage recipes and bookmarks
            

            // Close the dialog if it was opened inside a JDialog
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (window instanceof javax.swing.JDialog) {
                window.dispose();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete recipe.");
        }
    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
          Recipe recipe = controller.getRecipeById(currentRecipeId);
    if (recipe != null) {
        // Load data into update panel fields
        updatePanel.loadRecipeData(recipe);

        // Switch to update panel in CardLayout
        java.awt.CardLayout cl = (java.awt.CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "update");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Recipe data not found.");
    }
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (window instanceof javax.swing.JDialog) {
        window.dispose();
    }

    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
