/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cookbook;

import Model.Recipe;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Jay pradhan
 */
public class Home extends javax.swing.JFrame {
    
//    private JPanel home_panel;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
//        home_panel = new JPanel();
//        home_panel.setLayout(new BoxLayout(home_panel,BoxLayout.Y_AXIS));
//        add(home_panel);
        recipeDisplayPanel.setLayout(new GridLayout(0,5,15,15));
//        recipeDisplayPanel.setLayout(new BoxLayout(recipeDisplayPanel, BoxLayout.X_AXIS));
    jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    jScrollPane1.setViewportView(recipeDisplayPanel);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_panel = new javax.swing.JPanel();
        Popularthisweek_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recipeDisplayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Popularthisweek_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Popularthisweek_label.setForeground(new java.awt.Color(127, 1, 31));
        Popularthisweek_label.setText("Popular This Week");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        recipeDisplayPanel.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(recipeDisplayPanel);

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Popularthisweek_label, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Popularthisweek_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(home_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 670, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }
    public JPanel getRecipeDisplayPanel() {
    return recipeDisplayPanel;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Popularthisweek_label;
    public javax.swing.JPanel home_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel recipeDisplayPanel;
    // End of variables declaration//GEN-END:variables
public void displayRecipes(List<Recipe> recipes){
    recipeDisplayPanel.removeAll();
    
    for (Recipe recipe : recipes){
        JPanel recipeCard = createRecipeCard(recipe);
        recipeDisplayPanel.add(recipeCard);
//        JPanel recipeCard = new JPanel();
//        recipeCard.setLayout(new BoxLayout(recipeCard, BoxLayout.Y_AXIS));
//        recipeCard.setBorder(BorderFactory.createTitledBorder(recipe.getName()));
        
//        if(recipe.getImagePath()!= null && !recipe.getImagePath().isEmpty()){
//           File imageFile = new File(recipe.getImagePath());
//            if (imageFile.exists()) {
//                ImageIcon icon = new ImageIcon(recipe.getImagePath());
//                Image scaledImage = icon.getImage().getScaledInstance(150, 100, Image.SCALE_SMOOTH);
//                JLabel imageLabel = new JLabel(new ImageIcon(scaledImage));
//                recipeCard.add(imageLabel);
//            }
//        }
//
//        JLabel durationLabel = new JLabel("Duration: " + recipe.getDuration() + " mins");
//        JTextArea processArea = new JTextArea(recipe.getProcess());
//        processArea.setLineWrap(true);
//        processArea.setWrapStyleWord(true);
//        processArea.setEditable(false);
//        processArea.setOpaque(false);
//
//        recipeCard.add(durationLabel);
//        recipeCard.add(processArea);
//
//        recipeDisplayPanel.add(recipeCard);
    }

    recipeDisplayPanel.revalidate();
    recipeDisplayPanel.repaint();
} 
//         }
//                 createRecipeCard(recipe);
//         recipeDisplayPanel.add(recipeCard);
        
//     }
//     recipeDisplayPanel.revalidate();
//     recipeDisplayPanel.repaint();
// }

private JPanel createRecipeCard(Recipe recipe) {
    JPanel card = new JPanel();
    card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
    card.setPreferredSize(new Dimension(180, 220));
    card.setBorder(BorderFactory.createTitledBorder(recipe.getName()));
    card.setBackground(Color.WHITE);

    if (recipe.getImagePath() != null && !recipe.getImagePath().isEmpty()) {
        File imgFile = new File(recipe.getImagePath());
        if (imgFile.exists()) {
            ImageIcon icon = new ImageIcon(recipe.getImagePath());
            Image scaledImg = icon.getImage().getScaledInstance(150, 100, Image.SCALE_SMOOTH);
            JLabel imageLabel = new JLabel(new ImageIcon(scaledImg));
            card.add(imageLabel);
        }
    }

    JLabel durationLabel = new JLabel("Duration: " + recipe.getDuration() + " mins");
    JLabel categoryLabel = new JLabel("Category: " + recipe.getCategory());

    card.add(durationLabel);
    card.add(categoryLabel);

    return card;
}

}


