/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cookbook;

import DAO.RecipeDAO;
import Database.Database;
import Database.MySqlConnection;
import Model.Recipe;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import cookbook.Dashboard;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jay pradhan
 */
public class RecipeDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecipeDetailPanel
     */
   
    private Recipe currentRecipe;
    private java.awt.event.ActionListener backButtonListener;
    private boolean isCompleted = false;  // or fetch actual state from DB

public void setBackButtonListener(java.awt.event.ActionListener listener) {
    this.backButtonListener = listener;
}


public void setRecipe(Recipe recipe) {
    this.currentRecipe = recipe;
    loadRecipeDetails(recipe);
    
    
}

public Recipe getRecipe() {
    return currentRecipe;
}


    public RecipeDetailPanel() {
        initComponents();
    }
    public void loadRecipeDetails(Recipe recipe) {
    // Set title text
    titleLabel.setText(recipe.getName());

    // Set duration text
    durationLabel.setText("Duration: " + recipe.getDuration() + " mins");

    // Set process text in text area
    processArea.setText(recipe.getProcess());

    // Load and scale image for imageLabel
    if (recipe.getImagePath() != null && !recipe.getImagePath().isEmpty()) {
        File imageFile = new File(recipe.getImagePath());
        if (imageFile.exists()) {
            ImageIcon icon = new ImageIcon(recipe.getImagePath());
            Image scaledImage = icon.getImage().getScaledInstance(300, 200, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(scaledImage));
        } else {
            imageLabel.setIcon(null); // no image available
        }
    } else {
        imageLabel.setIcon(null); // no image path
    }
      if (recipe.isCompleted()) {
        MarkasComplete.setText("Marked as Complete");
        isCompleted = true;
    } else {
        MarkasComplete.setText("Mark as Complete");
        isCompleted = false;
    }
}
   private void toggleCompletion() {
    Database db = new MySqlConnection(); 
    RecipeDAO recipeDAO = new RecipeDAO(db);
    int recipeId = currentRecipe.getId();

    if (!isCompleted) {
        // Mark as complete: set reward to 2.5 (fixed)
        currentRecipe.setReward(2.5);
        MarkasComplete.setText("Marked as Complete");
    } else {
        // Unmark complete: set reward back to 0
        currentRecipe.setReward(0);
        MarkasComplete.setText("Mark as Complete");
    }

    isCompleted = !isCompleted;

    // Update reward in database
    recipeDAO.updateRecipeReward(recipeId, currentRecipe.getReward());
}

    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        processArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        MarkasComplete = new javax.swing.JButton();

        titleLabel.setText("jLabel1");

        imageLabel.setText("jLabel1");

        durationLabel.setText("jLabel1");

        processArea.setColumns(20);
        processArea.setRows(5);
        jScrollPane1.setViewportView(processArea);

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        MarkasComplete.setText("Mark as Complete");
        MarkasComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkasCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(durationLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageLabel)
                            .addComponent(titleLabel))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarkasComplete)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(MarkasComplete))
                .addGap(19, 19, 19)
                .addComponent(titleLabel)
                .addGap(52, 52, 52)
                .addComponent(durationLabel)
                .addGap(1, 1, 1)
                .addComponent(imageLabel)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Dashboard.Main_panel.getLayout();
cl.show(Dashboard.Main_panel, "home");

    System.out.println("Back pressed");
    
    }//GEN-LAST:event_backButtonMouseClicked

    private void MarkasCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkasCompleteActionPerformed
        // TODO add your handling code here:
        MarkasComplete.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        toggleCompletion();
    }
});
    }//GEN-LAST:event_MarkasCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MarkasComplete;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea processArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
