/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cookbook;

import DAO.RecipeDAO;
import Model.Recipe;
import controller.AdminDashboardController;

/**
 *
 * @author Jay pradhan
 */
public class update extends javax.swing.JPanel {

    /**
     * Creates new form update
     */
      private RecipeDAO recipeDAO;
    private AdminDashboardController controller;
    private int recipeId;  // <-- Move this here

    // ✅ Constructor
    public update(RecipeDAO recipeDAO, AdminDashboardController controller) {
        this.recipeDAO = recipeDAO;
        this.controller = controller;
        initComponents();
    }
    public update() {
        initComponents();
        this.controller = null;
    }
    

public void loadRecipeData(Recipe recipe) {
    this.recipeId = recipe.getId();
    titleField.setText(recipe.getName());
    durationField.setText(String.valueOf(recipe.getDuration()));
    areaField.setText(recipe.getProcess());
}
public void setController(AdminDashboardController controller) {
    this.controller = controller;
}

   




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();

        titleField.setText("jTextField1");
        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });

        durationField.setText("jTextField2");

        areaField.setColumns(20);
        areaField.setRows(5);
        jScrollPane1.setViewportView(areaField);

        jLabel1.setText("Title:");

        jLabel2.setText("Duration:");

        jLabel3.setText("Description:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(saveBtn)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveBtn)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
          String updatedTitle = titleField.getText();
    String durationText = durationField.getText();
    String updatedProcess = areaField.getText();

    if (updatedTitle.isEmpty() || durationText.isEmpty() || updatedProcess.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    int updatedDuration;
    try {
        updatedDuration = Integer.parseInt(durationText);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Duration must be a number.");
        return;
    }

    Recipe updatedRecipe = new Recipe(recipeId, updatedTitle, updatedDuration, updatedProcess, null); // Assuming image doesn't change

    boolean success = recipeDAO.updateRecipe(updatedRecipe);
    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Recipe updated successfully!");
        // Optionally close the panel or reload the home screen
        controller.loadRecipesToHome();
    controller.loadBookmarkedRecipes();
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to update recipe.");
    }
        
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaField;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
