/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cookbook;

import DAO.RecipeDAO;
import Model.Recipe;
import controller.AdminDashboardController;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jay pradhan
 */
public class update extends javax.swing.JPanel {

    /**
     * Creates new form update
     */
      private RecipeDAO recipeDAO;
    private AdminDashboardController controller;
    private int recipeId;  // <-- Move this here
    private String selectedImagePath = null;


    // ✅ Constructor
    public update(RecipeDAO recipeDAO, AdminDashboardController controller) {
        this.recipeDAO = recipeDAO;
        this.controller = controller;
        initComponents();
    }
    public update() {
        initComponents();
        this.controller = null;
    }
    

public void loadRecipeData(Recipe recipe) {
    this.recipeId = recipe.getId();
    titleField.setText(recipe.getName());
    durationField.setText(String.valueOf(recipe.getDuration()));
    areaField.setText(recipe.getProcess());
    category.setText(recipe.getCategory()); 
}
public void setController(AdminDashboardController controller) {
    this.controller = controller;
}

   




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chooseImgBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleField.setText("jTextField1");
        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });
        add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 27, -1, -1));

        durationField.setText("jTextField2");
        durationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationFieldActionPerformed(evt);
            }
        });
        add(durationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 67, -1, -1));

        areaField.setColumns(20);
        areaField.setRows(5);
        jScrollPane1.setViewportView(areaField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 116, -1, -1));

        jLabel1.setText("Title:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 30, -1, -1));

        jLabel2.setText("Duration:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 70, -1, -1));

        jLabel3.setText("Description:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 116, -1, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel4.setText("choose image:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        category.setText("jTextField2");
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel5.setText("Category:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        chooseImgBtn.setText("jButton1");
        chooseImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImgBtnActionPerformed(evt);
            }
        });
        add(chooseImgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
          String updatedTitle = titleField.getText();
    String durationText = durationField.getText();
    String updatedProcess = areaField.getText();

    if (updatedTitle.isEmpty() || durationText.isEmpty() || updatedProcess.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    int updatedDuration;
    try {
        updatedDuration = Integer.parseInt(durationText);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Duration must be a number.");
        return;
    }

    String updatedCategory = category.getText(); // ← fetch it
     if (selectedImagePath == null) {
            selectedImagePath = controller.getRecipeById(recipeId).getImagePath();
        }
Recipe updatedRecipe = new Recipe(recipeId, updatedTitle, updatedDuration, updatedProcess, selectedImagePath, updatedCategory);

 // Assuming image doesn't change

    boolean success = recipeDAO.updateRecipe(updatedRecipe);
    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Recipe updated successfully!");
        // Optionally close the panel or reload the home screen
        controller.loadRecipesToHome();
    controller.loadBookmarkedRecipes();
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to update recipe.");
    }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void durationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationFieldActionPerformed

    private void chooseImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImgBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        File destination = new File("images", selectedFile.getName());
        try {
            Files.copy(selectedFile.toPath(), destination.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            selectedImagePath = destination.getPath(); // Save the path for saving in DB later
            JOptionPane.showMessageDialog(this, "Image selected successfully!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to copy image.");
        }
    }
  
    }//GEN-LAST:event_chooseImgBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaField;
    private javax.swing.JTextField category;
    private javax.swing.JButton chooseImgBtn;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
